sudo: required
dist: trusty
before_install:
- chmod +x install-deps.sh
- ./install-deps.sh
script:
- chmod +x build-glossario.sh
- mkdir _travis-build
- ./build-glossario.sh _travis-build
deploy:
  provider: releases
  api_key:
    secure: [YOUR KEY]
  file:
  - _travis-build/Glossario.pdf
  skip_cleanup: true
  on:
    tags: true